# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Minimum' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Minimum

  target 'MinimumTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Charts'
    pod 'TinyConstraints'
    pod 'FSCalendar'
  end

  target 'MinimumUITests' do
    # Pods for testing
  end

end
